# Yoda theme for lazygit
# Based on yoda.nvim colorscheme
gui:
  # Color theme configuration
  theme:
    # Basic UI colors based on yoda dark theme
    activeBorderColor:
      - "#00dd88" # accent color (bright green)
      - bold
    inactiveBorderColor:
      - "#2a3a2a" # border color
    optionsTextColor:
      - "#d4d4d4" # fg color
    selectedLineBgColor:
      - "#0a2218" # selection color
    selectedRangeBgColor:
      - "#0f120f" # bg_highlight
    cherryPickedCommitBgColor:
      - "#2a2a1a" # diff_text
    cherryPickedCommitFgColor:
      - "#00dd88" # accent
    unstagedChangesColor:
      - "#ff6666" # red/error
    defaultFgColor:
      - "#d4d4d4" # fg color
    # Search and selection
    searchingActiveBorderColor:
      - "#00dd88" # accent
      - bold
    # File status colors
    addedFileColor:
      - "#00dd88" # green
    modifiedFileColor:
      - "#ffee58" # yellow/warning
    deletedFileColor:
      - "#ff6666" # red/error
    # Diff colors (keeping original git colors)
    diffAddedColor:
      - "#28a745" # git standard green
    diffModifiedColor:
      - "#ffee58" # yellow
    diffDeletedColor:
      - "#dc3545" # git standard red
    # Branch colors
    branchUpstreamColor:
      - "#7dd3c0" # cyan/number
    branchLogColor:
      - "#e6a3d0" # pink/magenta
  # Window background
  screenMode: "normal"
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible"
  # Mouse support
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  # Commit message length
  commitLength:
    show: true
  # Show file tree
  showFileTree: true
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  showBranchCommitHash: false
  # Spinner
  spinner:
    frames:
      - "|"
      - "/"
      - "-"
      - "\\"
    rate: 50
# Git configuration
git:
  paging:
    colorArg: always
    useConfig: false
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ""
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
# Update configuration
update:
  method: prompt
# Reporting
reporting: "undetermined"
# Disable update check
disableStartupPopups: false
# Custom commands for enhanced workflow
customCommands:
  - key: "<c-f>"
    command: "git difftool --no-symlinks --dir-diff {{.SelectedFile.Name}}"
    context: "files"
    description: "Open external diff tool"
  - key: "C"
    command: "git cz"
    context: "files"
    description: "Commit with commitizen"
    loadingText: "Preparing commitizen..."
  - key: "<c-p>"
    command: "git push --force-with-lease"
    context: "localBranches"
    description: "Force push with lease"
    loadingText: "Force pushing..."
# Keybinding configuration
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItem-alt: "k"
    nextItem-alt: "j"
    prevPage: ","
    nextPage: "."
    gotoTop: "<"
    gotoBottom: ">"
    scrollLeft: "H"
    scrollRight: "L"
    prevBlock: "<left>"
    nextBlock: "<right>"
    prevBlock-alt: "h"
    nextBlock-alt: "l"
    jumpToBlock: ["1", "2", "3", "4", "5"]
    nextMatch: "n"
    prevMatch: "N"
    optionMenu: <disabled>
    optionMenu-alt1: "?"
    select: "<space>"
    goInto: "<enter>"
    openRecentRepos: "<c-r>"
    confirm: "<enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdown>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    scrollUpMain-alt2: "<c-u>"
    scrollDownMain-alt2: "<c-d>"
    executeShellCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "]"
    prevTab: "["
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: "<c-s>"
    diffingMenu: "W"
    diffingMenu-alt: "<c-e>"
    copyToClipboard: "<c-o>"
    submitEditorText: "<enter>"
    extrasMenu: "@"
    toggleWhitespaceInDiffView: "<c-w>"
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
    openMergeTool: "M"
    openStatusFilter: "<c-b>"
  branches:
    createPullRequest: "o"
    viewPullRequestOptions: "O"
    checkoutBranchByName: "c"
    forceCheckoutBranch: "F"
    rebaseBranch: "r"
    renameBranch: "R"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    createTag: "T"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"
  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "c"
    cherryPickCopyRange: "C"
    pasteCommits: "v"
    tagCommit: "T"
    checkoutCommit: "<space>"
    resetCherryPick: "<c-R>"
    copyCommitMessageToClipboard: "<c-y>"
    openLogMenu: "<c-l>"
    viewBisectOptions: "b"
  stash:
    popStash: "g"
    renameStash: "r"
  commitFiles:
    checkoutCommitFile: "c"
  main:
    toggleDragSelect: "v"
    toggleDragSelect-alt: "V"
    toggleSelectHunk: "a"
    pickBothHunks: "b"
  submodules:
    init: "i"
    update: "u"
    bulkMenu: "b"
