name: Theme Preview

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Generate Theme Preview
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Generate theme preview
        uses: kuri-sun/nvim-theme-preview-action@v1
        with:
          theme-name: "yoda"
